trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

resources:
  containers:
  - container: 'postgres'
    image: 'postgres:15'
    ports:
    - 5432:5432
    env:
      POSTGRES_PASSWORD: 'postgrespassword'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'

variables:
  ArtifactName: 'WeddingWebsite-Postgres'
  ArtifactPath: '$(Pipeline.Workspace)'
  MigrationPath: 'WeddingWebsite-Backend/WeddingInvites'
  TestPath: 'WeddingWebsite-Backend/WeddingInvites.Test'
  AngularPath: 'WeddingWebsite-Angular'  

stages:
- template: build-postgres.yaml
  parameters:
    ArtifactName: '$(ArtifactName)'
    ArtifactPath: '$(ArtifactPath)'
    MigrationPath: '$(MigrationPath)'
    TestPath: '$(TestPath)'
    AngularPath: '$(AngularPath)'

- template: deploy-postgres.yaml
  parameters:
      ArtifactName: '$(ArtifactName)'
      ArtifactPath: '$(ArtifactPath)'
